interface IManaSimbols {
  [key: string]: any;
}

const ManaSimbols: IManaSimbols = {
  "0": require("./0.png"),
  "1": require("./1.png"),
  "2": require("./2.png"),
  "3": require("./3.png"),
  "4": require("./4.png"),
  "5": require("./5.png"),
  "6": require("./6.png"),
  "7": require("./7.png"),
  "8": require("./8.png"),
  "9": require("./9.png"),
  "10": require("./10.png"),
  "11": require("./11.png"),
  "12": require("./12.png"),
  "13": require("./13.png"),
  "14": require("./14.png"),
  "15": require("./15.png"),
  "16": require("./16.png"),
  "17": require("./17.png"),
  "18": require("./18.png"),
  "19": require("./19.png"),
  "20": require("./20.png"),
  "2B": require("./2B.png"),
  "2G": require("./2G.png"),
  "2R": require("./2R.png"),
  "2U": require("./2U.png"),
  "2W": require("./2W.png"),
  B: require("./B.png"),
  BG: require("./BG.png"),
  BP: require("./BP.png"),
  BR: require("./BR.png"),
  C: require("./C.png"),
  G: require("./G.png"),
  GP: require("./GP.png"),
  GU: require("./GU.png"),
  GW: require("./GW.png"),
  R: require("./R.png"),
  RG: require("./RG.png"),
  RP: require("./RP.png"),
  RW: require("./RW.png"),
  S: require("./S.png"),
  U: require("./U.png"),
  UB: require("./UB.png"),
  UP: require("./UP.png"),
  UR: require("./UR.png"),
  W: require("./W.png"),
  WB: require("./WB.png"),
  WP: require("./WP.png"),
  WU: require("./2.png"),
  X: require("./2.png"),
};

export default ManaSimbols;
